export const NAVIGATOR_SCREEN = {
  HOME: "HOME",
  HOME_SCREEN: "HOME_SCREEN",
  CAMPAIGN: "CAMPAIGN",
  DETAIL_CAMPAIGN: "DETAIL_CAMPAIGN",
  GAME: "GAME",
  SHAKE_PHONE: "SHAKE_PHONE",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  PROFILE: "PROFILE",
  REGISTER: "REGISTER",
};

export const GENDER_ENUM = {
  MALE: { text: "Nam" },
  FEMALE: { text: "Nữ" },
  OTHER: { text: "Khác" },
};
